// Code generated by controller-gen. DO NOT EDIT.
// operator/internal/api/v1alpha1/zz_generated.deepcopy.go

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of AppConfig into another AppConfig instance.
func (in *AppConfig) DeepCopyInto(out *AppConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of AppConfig.
func (in *AppConfig) DeepCopy() *AppConfig {
	if in == nil {
		return nil
	}
	out := new(AppConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *AppConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of AppConfigList into another AppConfigList instance.
func (in *AppConfigList) DeepCopyInto(out *AppConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of AppConfigList.
func (in *AppConfigList) DeepCopy() *AppConfigList {
	if in == nil {
		return nil
	}
	out := new(AppConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *AppConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of AppConfigSpec into another AppConfigSpec instance.
func (in *AppConfigSpec) DeepCopyInto(out *AppConfigSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of AppConfigSpec.
func (in *AppConfigSpec) DeepCopy() *AppConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AppConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of AppConfigStatus into another AppConfigStatus instance.
func (in *AppConfigStatus) DeepCopyInto(out *AppConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of AppConfigStatus.
func (in *AppConfigStatus) DeepCopy() *AppConfigStatus {
	if in == nil {
		return nil
	}
	out := new(AppConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies EnvVar into another EnvVar instance.
func (in *EnvVar) DeepCopyInto(out *EnvVar) {
	*out = *in
}

// DeepCopy returns a deep copy of EnvVar.
func (in *EnvVar) DeepCopy() *EnvVar {
	if in == nil {
		return nil
	}
	out := new(EnvVar)
	in.DeepCopyInto(out)
	return out
}
