apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/cert-manager/cert-manager/releases/download/v1.20.1/cert-manager.yaml
- clusterissuers.yaml

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --feature-gates=ExperimentalGatewayAPISupport=true
  target:
    kind: Deployment
    name: cert-manager
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-options: RespectIgnoreDifferences=true
        argocd.argoproj.io/ignore-differences: |
          {
            "kind": "Secret",
            "name": "cloudflare-api-token",
            "namespace": "cert-manager",
            "jsonPointers": ["/data"]
          }
  target:
    kind: Namespace
    name: cert-manager