apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd/application.yaml
  - argocd/certificate.yaml  # Add this line
  - cert-manager/application.yaml
  - cert-manager/cluster-issuer.yaml
  - cilium/application.yaml
  - cilium/l2-announcement-policy.yaml
  - monitoring/application.yaml
  - ../policies