apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: home-l2-policy
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  serviceSelector:
    matchLabels: {}
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  interfaces:
    - eth0