apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Homelab cluster workloads

  sourceRepos:
    - https://github.com/diogofrmota/swiss-post-project
    - https://helm.cilium.io
    - https://charts.jetstack.io
    - https://prometheus-community.github.io/helm-charts
    - https://argoproj.github.io/argo-helm
    - https://metallb.github.io/metallb
    - https://kyverno.github.io/kyverno

  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  syncWindows:
    - kind: deny
      schedule: '0 2 * * *'
      duration: 1h
      namespaces:
        - kube-system


