apiVersion: argoproj.io/v1alpha1
kind: AppProject # Limits which source repos and destination clusters/namespaces are allowed.
metadata:
  name: homelab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Homelab cluster workloads

  # Only this repository may be used as a source
  sourceRepos:
    - https://github.com/diogofrmota/swiss-post-project
    - https://helm.cilium.io
    - https://charts.jetstack.io
    - https://prometheus-community.github.io/helm-charts
    - https://argoproj.github.io/argo-helm
    - https://metallb.github.io/metallb
    - https://kyverno.github.io/kyverno

  # Only the local cluster is a valid destination
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'

  # Allow all core resource kinds
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  # Prevent accidental deletion of live resources
  syncWindows:
    - kind: deny # created for testing/ showcase, since this is a home server I will not be need a maintenance window
      schedule: '0 2 * * *'    # deny syncs between 02:00–03:00 (maintenance window)
      duration: 1h
      namespaces:
        - kube-system