apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: golang-scraper
  namespace: golang-scraper
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: golang-scraper
  endpoints:
    - port: metrics
      path: /metrics
      interval: 60s