apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - add-namespace-labels.yaml
  - disallow-privileged-containers.yaml
  - require-non-root.yaml
  - require-resource-limits.yaml