run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - exhaustive
    - noctx
    - bodyclose
    - contextcheck
    - unparam
    - dupl
    - gocritic

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/diogofrmota/custom-operator
  revive:
    rules:
      - name: exported
        severity: warning
  misspell:
    locale: US
  dupl:
    threshold: 150

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - dupl
        - unparam